// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	ioc2 "github.com/to404hanga/online_judge_judger/cmd/worker/ioc"
	"github.com/to404hanga/online_judge_judger/cmd/worker/service"
	"github.com/to404hanga/online_judge_judger/event"
	"github.com/to404hanga/online_judge_judger/ioc"
)

// Injectors from wire.go:

func BuildDependency() *service.JudgeService {
	logger := ioc.InitLogger()
	db := ioc.InitDB()
	cmdable := ioc.InitRedis()
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := event.NewSaramaProducer(syncProducer)
	judgeService := ioc2.InitJudgerWorkerService(logger, db, cmdable, producer)
	return judgeService
}
