// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	ioc2 "github.com/to404hanga/online_judge_judger/cmd/master/ioc"
	"github.com/to404hanga/online_judge_judger/cmd/master/service"
	"github.com/to404hanga/online_judge_judger/ioc"
)

// Injectors from wire.go:

func BuildDependency() *service.SubmissionService {
	logger := ioc.InitLogger()
	client := ioc.InitKafka()
	consumerGroup := ioc2.InitJudgerMasterConsumerGroup(client)
	cmdable := ioc.InitRedis()
	db := ioc.InitDB()
	cache := ioc2.InitLRUCache()
	submissionService := service.NewSubmissionService(logger, consumerGroup, cmdable, db, cache)
	return submissionService
}
