// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	ioc2 "github.com/to404hanga/online_judge_judger/cmd/resultcollector/ioc"
	"github.com/to404hanga/online_judge_judger/cmd/resultcollector/service"
	"github.com/to404hanga/online_judge_judger/ioc"
)

// Injectors from wire.go:

func BuildDependency() *service.ResultCollectorService {
	logger := ioc.InitLogger()
	client := ioc.InitKafka()
	consumerGroup := ioc2.InitResultCollectorConsumerGroup(client)
	db := ioc.InitDB()
	cmdable := ioc.InitRedis()
	rankingService := ioc2.InitRankingService(db, cmdable, logger)
	resultCollectorService := service.NewResultCollectorService(logger, consumerGroup, db, rankingService)
	return resultCollectorService
}
